// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD96HwU7Jexj1aYh1WxJON3HesKq_izCrs',
    appId: '1:768156337919:web:314c40a6371df9c25aeeca',
    messagingSenderId: '768156337919',
    projectId: 'attendent-app',
    authDomain: 'attendent-app.firebaseapp.com',
    storageBucket: 'attendent-app.firebasestorage.app',
    measurementId: 'G-HDFZQ8SZ08',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfRDvjzBqePSeQo7k34X8WjMtQvqLIVn4',
    appId: '1:768156337919:android:b386eaf3f13222595aeeca',
    messagingSenderId: '768156337919',
    projectId: 'attendent-app',
    storageBucket: 'attendent-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQajgf5wubgCEoA5FM3Ao6FV5aIvUmrnY',
    appId: '1:768156337919:ios:97b60e0ec099a35b5aeeca',
    messagingSenderId: '768156337919',
    projectId: 'attendent-app',
    storageBucket: 'attendent-app.firebasestorage.app',
    iosBundleId: 'com.example.attendanceApp',
  );
}
